/*
 * This program implements the Collatz conjecture (3n+1 problem).
 * It takes an integer input and prints the sequence generated by:
 * - dividing by 2 if the number is even
 * - multiplying by 3 and adding 1 if the number is odd
 * The loop continues until the number reaches 1.
 */

#include <stdio.h>

void decay(int *iNum) {
    int n = *iNum; 
    while (n > 1) {
        if (n % 2 == 0) {
            n = n / 2; 
        }
        else {
            n = (n * 3) + 1; 
        }
        printf("%d ", n); 
    } 
}

int main(){
    int t; 
    scanf("%d", &t); 
    decay(&t); 
    printf("\n"); 
    return 0;
}
